version: '3.9'

services:
  backend:
    build: ./energy_api
    container_name: django_backend
    volumes:
      - ./energy_api:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./energy-frontend
    container_name: vue_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
