# Generated by Django 5.2.1 on 2025-05-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Admin', 'Admin'), ('Commercial', 'Commercial'), ('Client', 'Client')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('siret', models.CharField(max_length=14)),
                ('siren', models.CharField(max_length=9)),
                ('adressePostal', models.TextField()),
                ('codePostal', models.CharField(max_length=10)),
                ('commune', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GAZ', 'GAZ'), ('ELEC', 'ELEC')], max_length=10)),
                ('numCompteur', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Validated', 'Validated')], default='Pending', max_length=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compte')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.societe')),
            ],
        ),
        migrations.CreateModel(
            name='CompteurGaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCompteur', models.CharField(max_length=50)),
                ('adresseCompteur', models.CharField(max_length=255)),
                ('consommation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.societe')),
            ],
        ),
        migrations.CreateModel(
            name='CompteurElec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCompteur', models.CharField(max_length=50)),
                ('adresseCompteur', models.CharField(max_length=255)),
                ('optionTarifaire', models.CharField(max_length=100)),
                ('puissance', models.IntegerField()),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.societe')),
            ],
        ),
        migrations.CreateModel(
            name='VentePro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=100)),
                ('numCompteur', models.CharField(max_length=50)),
                ('dateDebutFourniture', models.DateField()),
                ('dateFinFourniture', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.societe')),
            ],
        ),
    ]
